### ISSUE TITLE
Problems after migration from 0.7.4 to 0.8

### ISSUE THREAD

**Issue by dawid-nowak** [nats-io/nats.rs#109]
Hey all;
I have recently updated Nats dependency from 0.7.4 to 0.8 and I am my system stopped working. 

1. I am getting sys out output in the logs 
```
POLL_FILL_BUF
[/home/dawid/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-lite-1.11.0/src/io.rs:627] this.inner.as_mut().poll_read(cx, this.buf) = Ready(
    Ok(
        6,
    ),
)
>>> PING
 <<<
POLL_FILL_BUF
```

2. I am also getting error an error
```
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: Utf8Error { valid_up_to: 93, error_len: Some(1) }', /home/dawid/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-lite-1.11.0/src/io.rs:630:32
stack backtrace:
13:     0x561a6ef6e7f3 - core::option::expect_none_failed::hfcafefc70a7975bb
                               at src/libcore/option.rs:1272
  14:     0x561a6eb6784a - core::result::Result<T,E>::unwrap::h5f5b5aa469743cd0
                               at /home/dawid/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/libcore/result.rs:1005
  15:     0x561a6df3adb0 - <futures_lite::io::BufReader<R> as futures_io::if_std::AsyncBufRead>::poll_fill_buf::hdadca2e529b2a5bd
                               at /home/dawid/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-lite-1.11.0/src/io.rs:630
  16:     0x561a6df3771e - <&mut T as futures_io::if_std::AsyncBufRead>::poll_fill_buf::he171da15e47565c9
                               at /home/dawid/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-io-0.3.6/src/lib.rs:528
  17:     0x561a6df376ae - <&mut T as futures_io::if_std::AsyncBufRead>::poll_fill_buf::h72a7d46f2b2a5a47
                               at /home/dawid/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-io-0.3.6/src/lib.rs:528
  18:     0x561a6df2ad5b - futures_lite::io::read_until_internal::hffcc16481c7243ee
                               at /home/dawid/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-lite-1.11.0/src/io.rs:1578
  19:     0x561a6df3ce78 - <futures_lite::io::ReadUntilFuture<R> as core::future::future::Future>::poll::hc5a44bdc57b27932
                               at /home/dawid/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-lite-1.11.0/src/io.rs:1565
  20:     0x561a6dee8088 - nats::asynk::proto::decode::{{closure}}::hb64363651553c3ca
                               at /home/dawid/.cargo/registry/src/github.com-1ecc6299db9ec823/nats-0.8.0/src/asynk/proto.rs:55


```

**Comment by stjepang** [comment]
Can you do `cargo update -p futures-lite` and try again? Pretty sure this is due to an accidentally published wrong commit of futures-lite.

**Comment by dawid-nowak** [comment]
cool, that worked, thanks
