### ISSUE TITLE
`Context::get_consumer_from_stream` fails to decode Pull Consumer created via OpenTofu Provider

### ISSUE THREAD

**Issue by bengsparks** [nats-io/nats.rs#1353]
### Observed behavior

Despite setting up stream and consumer, and verifying their presence with the `nats` CLI,
`Context::get_consumer_from_stream` fails with

```
called `Result::unwrap()` on an `Err` value: Error { kind: Request, source: Some(Error { kind: Other, source: Some(Error("data did not match any variant of untagged enum Response", line: 0, column: 0)) }) }
```

### Expected behavior

The expected behavior is that fetching the created consumer succeeds without error, as the CLI seems to have no issue with this.

### Server and client version

Server:
```console
$ docker run -p 4222:4222 nats -js
[1] 2024/12/28 20:41:07.428376 [INF] Starting nats-server
[1] 2024/12/28 20:41:07.428407 [INF]   Version:  2.10.24
```

Client:
```
$ nats --version
0.1.6
```

### Steps to reproduce

<details>
  <summary>main.tf - Terraform Plan</summary>
  
```hcl
terraform {
  required_providers {
    jetstream = {
      source  = "nats-io/jetstream"
      version = "0.1.1"
    }
  }
}

provider "jetstream" {
  servers = "localhost:4222"
}

resource "jetstream_stream" "workflow_stream" {
  name      = "workflow"
  subjects  = ["workflow.>"]
  retention = "limits"
  max_msgs  = 1000
}

resource "jetstream_consumer" "echo_workflow" {
  stream_id = jetstream_stream.workflow_stream.id

  durable_name   = "echo"
  filter_subject = "workflow.echo"

  ack_policy    = "explicit"
  deliver_all   = true
  replay_policy = "instant"

  max_ack_pending = 100
}
```
</details>

<details>
    <summary>Creating stream and consumer with OpenTofu</summary>

```console
$ tree terraform/play                 
terraform/play
└── main.tf

$ tofu -chdir=./terraform/play apply -auto-approve
Plan: 2 to add, 0 to change, 0 to destroy.
jetstream_stream.workflow_stream: Creating...
jetstream_stream.workflow_stream: Creation complete after 0s [id=JETSTREAM_STREAM_workflow]
jetstream_consumer.echo_workflow: Creating...
jetstream_consumer.echo_workflow: Creation complete after 0s [id=JETSTREAM_STREAM_workflow_CONSUMER_echo]
```
</details>

<details>
    <summary>Checking the resources were created</summary>

```console
$ nats consumer info
[localhost] ? Select a Stream workflow
[localhost] ? Select a Consumer echo
Information for Consumer workflow > echo created 2024-12-28T21:55:04+01:00

Configuration:

                    Name: echo
               Pull Mode: true
          Filter Subject: workflow.echo
          Deliver Policy: All
              Ack Policy: Explicit
                Ack Wait: 30.00s
           Replay Policy: Instant
           Sampling Rate: 0%
         Max Ack Pending: 100
       Max Waiting Pulls: 512

State:

  Last Delivered Message: Consumer sequence: 0 Stream sequence: 0
    Acknowledgment Floor: Consumer sequence: 0 Stream sequence: 0
        Outstanding Acks: 0 out of maximum 100
    Redelivered Messages: 0
    Unprocessed Messages: 0
           Waiting Pulls: 0 of maximum 512
```
</details>

<details>
    <summary>main.rs & Cargo.toml</summary>

```rust
use async_nats::jetstream::{
    self,
    consumer::{pull, Consumer},
};

#[tokio::main]
async fn main() {
    tracing_subscriber::fmt()
        .with_file(true)
        .with_line_number(true)
        .init();

    let nats_url: String = "nats://localhost:4222".into();

    let conn = async_nats::connect(nats_url).await.unwrap();
    let jetstream = jetstream::new(conn);

    let consumer: Consumer<pull::Config> = jetstream
        .get_consumer_from_stream("echo", "workflow")
        .await
        .unwrap();

    println!("{:?}", consumer.cached_info())
}
```

```toml
[package]
name = "wat"
version = "0.1.0"
edition = "2021"

[dependencies]
async-nats = "0.38.0"
tokio = { version = "1.42.0", features = ["net", "rt-multi-thread", "macros"] }
tracing-subscriber = "0.3.19"
```
</details>

<details>
    <summary>Program Output</summary>

```console
$ RUST_LOG=trace c r

2024-12-28T21:01:56.636138Z  INFO async_nats: /Users/ben/.cargo/registry/src/index.crates.io-6f17d22bba15001f/async-nats-0.38.0/src/lib.rs:1041: event: connected
thread 'main' panicked at wat/src/main.rs:20:10:
called `Result::unwrap()` on an `Err` value: Error { kind: Request, source: Some(Error { kind: Other, source: Some(Error("data did not match any variant of untagged enum Response", line: 0, column: 0)) }) }
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

</details>

Interestingly enough, placing a `println!("{:#?}", request);` call [at this line](https://github.com/nats-io/nats.rs/blob/c958098ac68404af34d24f820d1650cd84f0b4e3/async-nats/src/client.rs#L506) adds the following output, which contains a seemingly valid consumer info response:

<details>
    <summary>println!</summary>

```rust
Ok(
    Message {
        subject: Subject {
            bytes: b"_INBOX.rMEBhy9L3rKmMn3PN9FwTh.rMEBhy9L3rKmMn3PN9FwQA",
        },
        reply: None,
        payload: b"{\"type\":\"io.nats.jetstream.api.v1.consumer_info_response\",\"stream_name\":\"workflow\",\"name\":\"echo\",\"created\":\"2024-12-28T20:55:04.660042204Z\",\"config\":{\"durable_name\":\"echo\",\"name\":\"echo\",\"deliver_policy\":\"all\",\"ack_policy\":\"explicit\",\"ack_wait\":30000000000,\"max_deliver\":-1,\"filter_subject\":\"workflow.echo\",\"replay_policy\":\"instant\",\"sample_freq\":\"0%\",\"max_waiting\":512,\"max_ack_pending\":100,\"num_replicas\":0},\"delivered\":{\"consumer_seq\":0,\"stream_seq\":0},\"ack_floor\":{\"consumer_seq\":0,\"stream_seq\":0},\"num_ack_pending\":0,\"num_redelivered\":0,\"num_waiting\":0,\"num_pending\":0,\"ts\":\"2024-12-28T21:01:56.636908811Z\"}",
        headers: None,
        status: None,
        description: None,
        length: 663,
    },
)
```
</details>

**Comment by bengsparks** [comment]
I've tracked it down.

The formatted JSON is
```
{
  "ack_floor": {
    "consumer_seq": 0,
    "stream_seq": 0
  },
  "config": {
    "ack_policy": "explicit",
    "ack_wait": 30000000000,
    "deliver_policy": "all",
    "durable_name": "echo",
    "filter_subject": "workflow.echo",
    "max_ack_pending": 100,
    "max_deliver": -1,
    "max_waiting": 512,
    "name": "echo",
    "num_replicas": 0,
    "replay_policy": "instant",
    "sample_freq": "0%" // !!!! <-----
  },
  "created": "2024-12-28T20:55:04.660042204Z",
  "delivered": {
    "consumer_seq": 0,
    "stream_seq": 0
  },
  "name": "echo",
  "num_ack_pending": 0,
  "num_pending": 0,
  "num_redelivered": 0,
  "num_waiting": 0,
  "stream_name": "workflow",
  "ts": "2024-12-29T00:44:59.822786149Z",
  "type": "io.nats.jetstream.api.v1.consumer_info_response"
}
```

```
thread 'main' panicked at wat/src/main.rs:30:54:
called `Result::unwrap()` on an `Err` value: Error { path: Path { segments: [Map { key: "config" }, Map { key: "sample_freq" }] }, original: Error("invalid digit found in string", line: 19, column: 3) }
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

`sample_freq` contains "%", which cannot be converted into a `u8`.
Which is funny, because the last person to find a `sample_freq` bug was also me 😂
