### ISSUE TITLE
Panic when creating consumer in the 

### ISSUE THREAD

**Issue by glueball** [nats-io/nats.rs#155]
#### NATS version (`grep 'name = "nats"' Cargo.lock -A 1`)
Crate version: 0.9.6

Server version:  2.2.0-beta.15  (it's the current synadia/jsm:latest image in docker hub, re-pulled it before trying to make sure)

#### rustc version (`rustc --version` - we support Rust 1.41 and up)
rustc 1.50.0 (cb75ad5db 2021-02-10)

#### OS/Container environment:
Windows 10

#### Steps or code to reproduce the issue:

Code:
https://pastebin.com/1N0huWGd

Run and execute it.

#### Expected result:

No panics

#### Actual result:

The first time the code runs it panics with:

```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Custom { kind: InvalidData, error: Error("data did not match any variant of untagged enum ApiResponse", line: 0, column: 0) }', src\main.rs:47:89
stack backtrace:
   0: std::panicking::begin_panic_handler
             at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b\/library\std\src\panicking.rs:493
   1: core::panicking::panic_fmt
             at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b\/library\core\src\panicking.rs:92
   2: core::option::expect_none_failed
             at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b\/library\core\src\option.rs:1268
   3: core::result::Result<nats::jetstream::Consumer, std::io::error::Error>::unwrap<nats::jetstream::Consumer,std::io::error::Error>
             at C:\Users\pod\.rustup\toolchains\stable-x86_64-pc-windows-msvc\lib\rustlib\src\rust\library\core\src\result.rs:973
   4: jetstream_test::main
             at .\src\main.rs:47
```

The panic occurs at the line with the `Consumer::create_or_open` call.

However, I can see that the stream and the consumer are created

```
~ # nats --server=localhost stream ls
Streams:

        testing

~ # nats --server=localhost stream info testing
Information for Stream testing

Configuration:

             Subjects: testing.*
     Acknowledgements: true
            Retention: File - Limits
             Replicas: 1
       Discard Policy: Old
     Duplicate Window: 0s
     Maximum Messages: unlimited
        Maximum Bytes: unlimited
          Maximum Age: 0s
 Maximum Message Size: unlimited
    Maximum Consumers: unlimited

State:

            Messages: 0
               Bytes: 0 B
            FirstSeq: 0
             LastSeq: 0
    Active Consumers: 1
```

(Note that I expected 3600s, or at least 3,6s if it is interpreted in ms, for the Duplicate Window setting)

```
~ # nats --server=localhost consumer info
? Select a Stream testing
? Select a Consumer testing_1_durable
Information for Consumer testing > testing_1_durable

Configuration:

        Durable Name: testing_1_durable
           Pull Mode: true
      Filter Subject: testing.testing
         Deliver All: true
          Ack Policy: Explicit
            Ack Wait: 2µs
       Replay Policy: Instant

State:

  Last Delivered Message: Consumer sequence: 0 Stream sequence: 0
    Acknowledgment floor: Consumer sequence: 0 Stream sequence: 0
        Pending Messages: 0
    Redelivered Messages: 0
```

The second, and subsequent times I run the same code, it works. I can see the "Listening" printf.

**Comment by spacejam** [comment]
I believe this is an issue that is resolved by using one of the newer release candidates for JS
