### ISSUE TITLE
Panic when processing JS message

### ISSUE THREAD

**Issue by glueball** [nats-io/nats.rs#156]
#### NATS version (`grep 'name = "nats"' Cargo.lock -A 1`)
Crate version: 0.9.6

Server version:  2.2.0-beta.15  (it's the current synadia/jsm:latest image in docker hub, re-pulled it before trying to make sure)

#### rustc version (`rustc --version` - we support Rust 1.41 and up)
rustc 1.50.0 (cb75ad5db 2021-02-10)

#### OS/Container environment:
Windows 10

#### Steps or code to reproduce the issue:

Code (same as the other issue):
https://pastebin.com/1N0huWGd

Compile and execute it (twice, due to #155).

Open a shell to the container running NATS and execute:

```
~ # nats --server=localhost pub testing.testing "Test 1,2,3"
11:51:33 Published 10 bytes to "testing.testing"
```

#### Expected result:

The message is correctly received.

#### Actual result:

The program panics at the `consumer.process` line:

```
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', C:\Users\pod\.cargo\registry\src\github.com-1ecc6299db9ec823\nats-0.9.6\src\jetstream.rs:874:57
stack backtrace:
   0: std::panicking::begin_panic_handler
             at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b\/library\std\src\panicking.rs:493
   1: core::panicking::panic_fmt
             at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b\/library\core\src\panicking.rs:92
   2: core::panicking::panic
             at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b\/library\core\src\panicking.rs:50
   3: core::option::Option<nats::jetstream_types::JetStreamMessageInfo>::unwrap<nats::jetstream_types::JetStreamMessageInfo>
             at C:\Users\pod\.rustup\toolchains\stable-x86_64-pc-windows-msvc\lib\rustlib\src\rust\library\core\src\option.rs:386
   4: nats::jetstream::Consumer::process<tuple<>,closure-0>
             at C:\Users\pod\.cargo\registry\src\github.com-1ecc6299db9ec823\nats-0.9.6\src\jetstream.rs:874
   5: jetstream_test::main
             at .\src\main.rs:52
   6: core::ops::function::FnOnce::call_once<fn(),tuple<>>
             at C:\Users\pod\.rustup\toolchains\stable-x86_64-pc-windows-msvc\lib\rustlib\src\rust\library\core\src\ops\function.rs:227
```

**Comment by spacejam** [comment]
0.9.7 is now published that includes better error output about why this path fails to parse. I believe the solution is to update your nats-server, as some things have changed before the release / commitments to stability

**Comment by glueball** [comment]
Confirmed, it is fixed in 0.9.7 and using the `synadia/jsm:nightly` image from docker hub.
